### ISSUE TITLE
Setup development and production environment

### ISSUE THREAD

**Issue by hlac** [TheOneRed/McMasterGame#4]
- Try to mirror the development production environment as much as possible.
- Get one person to install, setup, configure and document the steps to setting up a development.  Disseminate the set of instructions to everyone else.
- Setting up a development extracts the essential components from the production environment.  E.g., instead going to the cloud, your development environment goes through localhost.
- Test that setup is correct for production environment (communication, authentication, firewall).

**Comment by antonybogun** [comment]
1. Download and install Node.js 
[Node.js](https://nodejs.org/en/download/)

2. Download and install MongoDB
[MongoDB](https://www.mongodb.com/download-center?jmp=nav)

3. Test Start of MongoDB following "Start mongod processes":
[Start MongoDB](https://docs.mongodb.com/manual/tutorial/manage-mongodb-processes/)

4. Install Nodemon
[Nodemon Installation] (https://nodemon.io/)

5. Install Bower
[Bower Installation](https://bower.io/)

6. Install Express (globally preferred)
[Express installation](https://expressjs.com/en/starter/installing.html)

7. After pulling a project install dependencies by running
`npm install`

8. As a IDE Visual Studio Code preferred:
[VS Code Downloading](http://code.visualstudio.com/Download)

9. Helpful VS Code Extensions:
[HTML CSS Class Completion](https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion)
[EJS support](https://marketplace.visualstudio.com/items?itemName=QassimFarid.ejs-language-support)
[JS-CSS-HTML Formatter](https://marketplace.visualstudio.com/items?itemName=lonefy.vscode-JS-CSS-HTML-formatter)
